### ISSUE TITLE
QuestPointer/QuestPointer.lua:164: Usage: HaveQuestData(questID

### ISSUE THREAD

**Issue by yoshimo** [kemayo/wow-questpointer#7]
12x QuestPointer/QuestPointer.lua:164: Usage: HaveQuestData(questID
[string "=[C]"]: in function `HaveQuestData'
[string "@QuestPointer/QuestPointer.lua"]:164: in function `UpdateWorldPOIs'
[string "@QuestPointer/QuestPointer.lua"]:109: in function <QuestPointer/QuestPointer.lua:88>
[string "=(tail call)"]: ?

Locals:
(*temporary) = nil

**Comment by kemayo** [comment]
Could you tell me what zone you were in when this happened?

**Comment by yoshimo** [comment]
Suramar

**Comment by kemayo** [comment]
Bit of a strange one, since it means that the API function to request quests on that map returned something without a quest ID. If it happened just in a flash right when you zoned in, it *might* mean that there was a momentary data-not-yet-loaded-from-server issue. I can add a guardrail to stop the error, at least.

**Comment by yoshimo** [comment]
https://github.com/smaitch/Grail/issues/365
looks like wow changed the api call on the ptr

**Comment by kemayo** [comment]
Ah, yes, being on the PTR would indeed be useful information. 😂
